[package]
name = "funding_history"
version = "0.1.0"
edition = "2024"

[dependencies]
hyperliquid_rust_sdk = "0.6.0"
tokio = "1.47.1"
csv = "1.3.1"
serde = "1.0.219"
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = "1.0.143"